### PR TITLE
Include detection of OpenRC (Gentoo Linux) and automatically (un)install files

### PR DESCRIPTION
**Pull request by MegaV0lt**
I made some changes also to the log2ram script for better logging. On my Gen2VDR (Gentoo) it looks good after first tests. On systemd it should behave like before.

If you have suggestions, please let me know.

### CODE REVIEW

**Comment by azlux** [comment]
Hi,
Thank for the push.
Be careful, the script was bash and dash compatible. I need to read the docs to be sure it's dash compatible.

**Comment by MegaV0lt** [comment]
It should be compatible, at least shellcheck doesn't complain

**Comment by MegaV0lt** [comment]
You can paste the code at shellcheck.net and edit the first line to /bin/dash. Shellcheck then test it for compatibility...

**Comment by MegaV0lt** [comment]
Just made the test at shellckeck. Everything looks good. i fixed a redirect error

**Pull request merged**
