### PR TITLE
Use == instead of = for string comparisons

### PR DESCRIPTION
**Pull request by Sailing74**
In if-statements, I think string comparisons only work, if the operator == is used.

### CODE REVIEW

**Comment by Sailing74** [comment]
Sorry, this won't work as submitted, as it would require == "true" instead of == true...

**Comment by azlux** [comment]
The code `if [ "$USE_RSYNC" = true ]; then` is for bash and dash. If you use the `==` ,only bash will support it.

**Comment by Sailing74** [comment]
Yes, as mentioned, the change doesn't work.

I'm still trying to figure out why, on some machines, at some times sychronization back to disk fails. On these machines, I can run the rsync command manually, and it works. So I thought that the if test before that had an error, but that doesn't appear to be the case...

So I'll keep searching.

**Comment by azlux** [comment]
You can try to have log of `cp` and `rsync`.
Add `--verbose` to the `cp` command.
(Rsync have already the verbose option enabled)

**Pull request closed without merging**
